version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
